<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{99369a3d-4dc6-470f-a43b-a616750e939a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Manual_Automatic:BOOL;
	Visible:BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Stop();
Emergency_Stop();
Automatic_Or_Manual();
Visible:=not gvl.ixA;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="35" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="43" Count="0" />
      <LineId Id="49" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>